version: '3'

# 下面service固定ip
# 防止重启 -> 导致ip改变 -> 其他容器本地DNS缓存无改变 -> 导致无法解析域名 -> 容器之间无法通信
networks:
  class_web_net:
    ipam: 
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1

services:

  # 后端
  go_web:
    image: ${GO_WEB_IMAGE}
    container_name: go_web
    restart: always
    working_dir: /go_web
    volumes: 
      - ./goweb:/go_web
    environment: 
      - TZ=${SERVICE_AREA}
    networks: 
      class_web_net:
        ipv4_address: 172.19.0.100
    ports:
      - "${GO_WEB_PORT}:8080"
    command: 
      - sh
      - -c 
      - |
        sh is_env_has_change.sh
        go build -o main main.go
        ./main
  
  # 前端环境编译
  vue_admin_env:
    image: ${VUE_ADMIN_ENV_IMAGE}
    container_name: vue_admin_env
    networks: 
      class_web_net:
        ipv4_address: 172.19.0.106
    working_dir: /vue-admin
    volumes: 
      - ./vue-element-admin:/vue-admin
    command: 
      - sh
      - -c
      - |
        sh is_env_has_change.sh
        npm run build:prod

  # 前端
  vue_admin_nginx:
    image: ${VUE_ADMIN_NGINX_IMAGE}
    container_name: vue_admin_nginx
    working_dir: /vue-admin
    restart: always
    volumes: 
      - ./vue-element-admin:/vue-admin
    environment: 
      - TZ=${SERVICE_AREA}
    networks: 
      class_web_net:
        ipv4_address: 172.19.0.101
    ports: 
      - "${VUE_ADMIN_NGINX_PORT}:80"
    depends_on: 
      - vue_admin_env
    command: 
      - sh
      - -c
      - |
        sh wait_node_env_end.sh
        cp nginx.conf /etc/nginx/conf.d/default.conf
        cp -r dist/* /usr/share/nginx/html
        nginx -g "daemon off;"
        
  # 数据库
  postgresql:
    image: ${POSTGRES_IMAGE}
    container_name: postgresql
    restart: always
    networks: 
      class_web_net:
        ipv4_address: 172.19.0.102
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - PGTZ=${SERVICE_AREA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_SOURCE_PATH}:/var/lib/postgresql/data

