version: '3'
services:

  goweb:
    build: ./goweb
    volumes:
      - ./goweb/:/goweb
    ports:
      - "8080:8080"
  
  vue_admin_env:
    image: ${VUE_ADMIN_ENV_IMAGE}


  vue_admin_nginx:
    build: ./vue-element-admin
    volumes: 
      - ./vue-element-admin/:/vue-admin
    ports: 
      - "9999:80"

  jenkins:
    image: ${JENKINS_IMAGE}
    user: ${JENKINS_USER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JENKINS_HOME}:/var/jenkins_home/
      - ${JENKINS_SOURCE_PATH}:${JENKINS_TARGET_PATH}
      - ${GIT_SSH_PATH}:/${JENKINS_USER}/.ssh/
      - ${DOCKER_COMPOSE_PATH}:/usr/local/bin/docker-compose
      - ${DOCKER_PATH}:/usr/bin/docker
    ports:
      - "${JENKINS_OPEN_PORT}:8080"
      - "50000:50000"
