version: '3'
services:

  goweb:
    build: .
    volumes:
      - ./:/goweb
    ports:
      - "8080:8080"

  jenkins:
    image: jenkinsci/blueocean:latest
    user: root
    volumes:
      - ~/jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/:/myhome
      - ~/.ssh/:/root/.ssh/
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    ports:
      - "8888:8080"
      - "50000:50000"
